/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dvqffglycnsiebxgbuni"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2cWZmZ2x5Y25zaWVieGdidW5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1ODQ1MzgsImV4cCI6MjA4NDE2MDUzOH0.-4ViRHkqthaQ3QJfteK5S8ErAcwr2KVgLzsX-ioXWcY"